language: c

# Let's build everything for now; comment this out
#branches:
#  only:
#    - master

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - texlive
      - qttools5-dev-tools
      - libqt5sql5-sqlite
  homebrew:
    packages:
      - octave
      - qt
      - findutils

env:
  global:
    - OCTAVE=octave

matrix:
  include:
    - os: linux
      dist: xenial
      env: 
        - dist="Xenial 16.x"
        - OCTAVE_VER=4.2
    - os: linux
      dist: xenial
      env: 
        - dist="Xenial 16.x"
        - OCTAVE_VER=4.4
        - OCTAVE="flatpak run org.octave.Octave --no-gui"
    - os: osx
      osx_image: xcode10.1
      env: 
        - dist="Octave 4.4"
    - os: osx
      osx_image: xcode10
      env: dist="Octave 4.4"
    - os: osx
      osx_image: xcode9.4
      env: dist="Octave 4.4"

install:
  # Install Octave 4.2/4.4, even if it's not the default
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dev-tools/install-new-octave-ubuntu.sh; fi
  # Force linkage of gcc so octave can find gfortran
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link gcc; true; fi  

script:
  - which octave
  - octave --version
  - make local
  # Don't test on local; this package isn't set up for its
  #- make test
  - make dist
  - $OCTAVE --no-gui --eval "pkg install ./target/control-3.1.0.tar.gz"
  - $OCTAVE --no-gui --eval "pkg load control; pkg unload control"
  - $OCTAVE --no-gui --eval "pkg load control; my_run_tests_and_exit ./inst"
  - $OCTAVE --no-gui --eval "pkg uninstall control"
