language: c

# Let's build everything for now; comment this out
#branches:
#  only:
#    - master

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - texlive
      - qttools5-dev-tools
      - libqt5sql5-sqlite
  homebrew:
    taps:
      - homebrew/cask-versions
      - octave-app/octave-app-bases
      - octave-app/octave-app-openblas
    packages:
      - qt
      - findutils
      - pstree
    casks:
      - java8

env:
  global:
    - OCTAVE=octave
    - OCTAVE_VER=4.4
    - HOMEBREW_NO_AUTO_UPDATE=1
    - OCT_PKG=control
    - OCT_PKG_VER=3.1.0

matrix:
  include:
    - os: linux
      dist: xenial
      env: 
        - dist="Xenial 16.x"
        - OCTAVE="flatpak run org.octave.Octave"
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
      env: 
        - OCTAVE_BLAS=openblas
    - os: osx
      osx_image: xcode10
      env: 
        - OCTAVE_BLAS=openblas

install:
  # Install Octave 4.2/4.4, even if it's not the default in apt-get
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dev-tools/install-octave-ubuntu.sh; fi
  # Force linkage of gcc so octave can find gfortran
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link gcc; true; fi
  # Install Octave for macOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./dev-tools/install-octave-macos.sh; fi

after_install:
  - echo "Octave installation results:"
  - brew info "$formula"
  - echo "Formula prefix: $(brew --prefix $formula)"
  - which octave
  - ls -l "$(which octave)"
  - which mkoctfile
  - ls -l "$(which mkoctfile)"

script:
  - echo PATH=$PATH
  - find ~/bin
  - ls -l ~/bin/octave
  - ls -l ~/bin/mkoctfile
  - $OCTAVE --eval "ver"
  - make dist
  - $OCTAVE --no-gui --eval "pkg install ./target/${OCT_PKG}-${OCT_PKG_VER}.tar.gz"
  - $OCTAVE --no-gui --eval "pkg load ${OCT_PKG}; pkg unload ${OCT_PKG}"
  - $OCTAVE --no-gui --eval "pkg load ${OCT_PKG}; my_run_tests_and_exit ${OCT_PKG}"
  # Special tests for control package
  - $OCTAVE --no-gui --eval "pkg load ${OCT_PKG}; test('ltimodels', 'verbose', 'stdout')"
  - $OCTAVE --no-gui --eval "pkg load ${OCT_PKG}; test('bstmodred', 'verbose', 'stdout')"
  - $OCTAVE --no-gui --eval "pkg uninstall ${OCT_PKG}"
